### ISSUE TITLE
Devlog - ToDo

### ISSUE THREAD

**Issue by H-ymt** [H-ymt/devlog#1]
## Task
- [x] ダークモード[（参考記事）](https://kyoya.dev/posts/blog05/)
- [x] View Transitions API
- [x] ブログ記事内の目次を動的に生成
- [ ] お問い合わせフォーム（SSGForm）
- [ ] Google Analyticsの導入
- [x] 動的OGP生成
- [ ] 全文検索（[Pagefind](https://pagefind.app/)）
- [ ] Zennの一覧ページだけSSRにする（[参考記事](https://note.com/ru9pp/n/nae56894c1b9d)）

## 参考にしたWebサイト
- [Lucide](https://lucide.dev/)
- [Zenn](https://zenn.dev/)

## アイコン・ロゴ素材
- [Basicons](https://basicons.xyz/)

**Comment by H-ymt** [comment]
一旦、クローズ
